image_width: 640
samples_per_pixel: 50
max_depth: 20
camera:
  look_from:
    x: 0.0
    y: 0.0
    z: 10.0
  look_at:
    x: 0.0
    y: 0.0
    z: 0.0
  v_up:
    x: 0.0
    y: 1.0
    z: 0.0
  vertical_fov_deg: 20.0
  aspect_ratio: 1.25
  aperture: 0.1
  focus_distance: 10.0
objects:
  objects:
  - center:
      x: 0.0
      y: -100.5
      z: -1.0
    radius: 100.0
    material:
      type: Lambertian
      albedo:
        x: 0.8
        y: 0.8
        z: 0.0
  - center:
      x: 0.0
      y: 0.0
      z: -1.0
    radius: 0.5
    material:
      type: Lambertian
      albedo:
        x: 0.1
        y: 0.2
        z: 0.5
  # This and the next one together creates a glass factor
  - center:
      x: -1.0
      y: 0.0
      z: -1.0
    radius: 0.5
    material:
      type: Dielectric
      ir: 1.5
  - center:
      x: -1.0
      y: 0.0
      z: -1.0
    radius: -0.4
    material:
      type: Dielectric
      ir: 1.5
  - center:
      x: 1.0
      y: 0.0
      z: -1.0
    radius: 0.5
    material:
      type: Metal
      albedo:
        x: 0.8
        y: 0.6
        z: 0.2
      fuzz: 0.2
