image_width: 400
samples_per_pixel: 400
max_depth: 50
camera:
  look_from:
    x: 26.0
    y: 3.0
    z: 6.0
  look_at:
    x: 0.0
    y: 2.0
    z: 0.0
  v_up:
    x: 0.0
    y: 1.0
    z: 0.0
  vertical_fov_deg: 20.0
  aspect_ratio: 1.25
  aperture: 0.1
  focus_distance: 10.0
scene:
  type: SimpleLight
